name: rjwada

description: A new Flutter project.

publish_to: none

version: 1.0.0+1


environment: {sdk: '>=2.18.0 <3.0.0'}


dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.5
  image_picker: ^0.8.5+3
  get: ^4.6.5
  lottie: ^1.0.1
  http: ^0.13.5
  image_cropper: ^3.0.0
  flutter_image_compress: ^1.1.2

  firebase_core: ^1.21.1
  intl_phone_field: ^3.1.0
  firebase_auth: ^3.7.0
  pinput: ^2.2.12
  connectivity_plus: ^2.3.6
  internet_connection_checker: ^0.0.1+4
  overlay_support: ^2.0.1
  flutter_unity_widget: ^2022.2.0
  pointer_interceptor: ^0.9.3+2



dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.1


flutter: {uses-material-design: true}
